### ISSUE TITLE
retrieve contract sources from etherscan in support of event/function named parameter scanning

### ISSUE THREAD

**Issue by allenday** [volsa/etherface#11]
In support of #10

**Comment by volsa** [comment]
This is kinda covered in #10. The current approach to scraping function, event and error signatures from source code consists of finding these on Etherscan and GitHub. Once found the parser extracts these signatures with RegEx and inserts them into the database. To support mapping named parameters to their signatures we would need to extract these and insert them into the database also. Retrieving and scanning contract sources are done in one step though, therefore closing this in favor of #10.
