### ISSUE TITLE
⚠️ api.etherface.io Certifacte has expired

### ISSUE THREAD

**Issue by pldespaigne** [volsa/etherface#22]
Let's Encrypt certificate for api.etherface.io has expired yesterday (Jun 25).

This break all my calls to the api, could you please renew the certificate and maybe even enable automatic renewal for next times.

Etherface is a really awesome project, please keep up the good work, and let me know if I can be of any help ❤️

**Comment by volsa** [comment]
Weird, I could swear the certificate would expire in August or so. I'll see if I can fix it today - thanks for the issue.

**Comment by volsa** [comment]
Should be fixed; auto-renewal isn't activated yet though but I'm assuming a simple cron-job is all it needs?

**Comment by pldespaigne** [comment]
Thanks a lot for fixing that fast 🙏

About automatic renewal I'm not sure, but I think a cron job will work, if you are using apache/nginx here is a [tuto](https://www.baeldung.com/linux/letsencrypt-renew-ssl-certificate-automatically).
