### ISSUE TITLE
docs for github token 

### ISSUE THREAD

**Issue by allenday** [volsa/etherface#5]
What type of token needs to be generated?
- Fine-grained tokens
- Tokens (classic)
What permissions need to be granted to the token?

I'm getting many log messages like:
`[21.11.2022; 07:15:03] [INFO] Search ratelimit drained, sleeping one minute to reset`
and while the fourbyte and etherscan tables are populating, the table `mapping_signature_github` is not. So I'm assuming this message is related to the github scraper/fetcher.

**Comment by allenday** [comment]
tidied up a bit and sent a PR, see https://github.com/volsa/etherface/pull/6

**Comment by volsa** [comment]
Thanks!
